// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wb_kernel_cpp
List wb_kernel_cpp(NumericMatrix rain, NumericMatrix evap, NumericVector soilcp, NumericVector soilsat, NumericVector avail0);
RcppExport SEXP _wbkernel_wb_kernel_cpp(SEXP rainSEXP, SEXP evapSEXP, SEXP soilcpSEXP, SEXP soilsatSEXP, SEXP avail0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rain(rainSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type evap(evapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soilcp(soilcpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soilsat(soilsatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type avail0(avail0SEXP);
    rcpp_result_gen = Rcpp::wrap(wb_kernel_cpp(rain, evap, soilcp, soilsat, avail0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wbkernel_wb_kernel_cpp", (DL_FUNC) &_wbkernel_wb_kernel_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_wbkernel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
