# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wb_kernel_cpp <- function(rain, evap, soilcp, soilsat, avail0) {
    .Call(`_wbkernel_wb_kernel_cpp`, rain, evap, soilcp, soilsat, avail0)
}

