#!/usr/bin/env Rscript
# scripts/generate_threshold_table.R
# ==================================
# Issue #20. The live V1 "Evaluate Climate Risks" notebook states NTx35 severe = "> 20 days"; the
# pipeline threshold is and always has been **14**. Hand-written prose drifted from the metadata it
# claims to describe, and nothing detected it. The fix is not to correct the sentence - it is to stop
# hand-writing the numbers.
#
# This generates the threshold table from the files R/2 actually classifies with:
#   metadata/haz_classes.csv    thresholds per index x severity x crop/species
#   metadata/haz_metadata.csv   units, hazard type, direction
#   metadata/ecocrop.csv        the crop-specific heat families (formulas mirrored from R/2 §0.2.2.1)
#
# Outputs (both committed, so a reviewer sees the diff when a threshold moves):
#   metadata/published_thresholds.csv   machine-readable, one row per index x class x crop
#   metadata/published_thresholds.md    the table for the notebook footer, generated
#
# The notebook text lives in AdaptationAtlas/atlas_notebooksV1 (Brayden). This repo's job is to
# produce the table and the provenance; dropping it into the notebook is a relay.
#
# Usage: Rscript scripts/generate_threshold_table.R
suppressPackageStartupMessages({ library(data.table) })
root <- if (nzchar(Sys.getenv("project_dir"))) Sys.getenv("project_dir") else {
  fa <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(fa)) dirname(dirname(normalizePath(sub("^--file=", "", fa[1])))) else getwd()
}
md <- function(...) cat(sprintf(...), file = OUT_MD, append = TRUE)

cls  <- fread(file.path(root, "metadata", "haz_classes.csv"))
meta <- fread(file.path(root, "metadata", "haz_metadata.csv"))
eco  <- fread(file.path(root, "metadata", "ecocrop.csv"))
spam <- fread(file.path(root, "metadata", "SpamCodes.csv"))

# Units and hazard type come from haz_metadata, keyed on variable.code AND direction - PTOT and TAVG
# each have two rows (PTOT: wet when `>`, dry when `<`; TAVG: heat when `>`, cold when `<`). Joining
# on the code alone cross-produces them and mislabels the hazard type, which is what the first run of
# this script did: 114 rows instead of 103, with TAVG appearing as both "cold" and "heat".
u <- unique(meta[, .(index_name = variable.code, direction, unit = base_unit, type)])
.n_before <- nrow(cls)
d <- merge(cls, u, by = c("index_name", "direction"), all.x = TRUE)
if (nrow(d) != .n_before) stop(sprintf("the haz_metadata join changed the row count (%d -> %d): a key is not unique, so some thresholds are duplicated", .n_before, nrow(d)))
d[, severity := factor(description, levels = c("Moderate", "Severe", "Extreme"))]
setorder(d, type, index_name, crop, severity)

## ----------------------------------------------------------------- the generated CSV
OUT_CSV <- file.path(root, "metadata", "published_thresholds.csv")
out <- d[, .(hazard_type = type, index = index_name, applies_to = crop, severity = as.character(severity),
             direction, threshold, unit)]
fwrite(out, OUT_CSV)
cat(sprintf("wrote %s (%d rows)\n", OUT_CSV, nrow(out)))

## ----------------------------------------------------------------- the generated markdown
OUT_MD <- file.path(root, "metadata", "published_thresholds.md")
unlink(OUT_MD)
wide <- dcast(d, type + index_name + crop + direction + unit ~ severity, value.var = "threshold")
fmt <- function(x, dir, unit) ifelse(is.na(x), "—",
  ifelse(is.na(unit) | unit == "unitless", sprintf("%s %s", dir, x), sprintf("%s %s %s", dir, x, unit)))

md("# Hazard thresholds, as the pipeline classifies them\n\n")
md("**Generated by `scripts/generate_threshold_table.R` on %s — do not hand-edit.**\n", format(Sys.Date()))
md("Source: `metadata/haz_classes.csv` (thresholds), `metadata/haz_metadata.csv` (units and hazard type).\n\n")
md("A hazard fires for a cell-year when the index crosses the threshold in the stated direction.\n")
md("The three severity classes are nested in intent but are classified independently.\n\n")
md("> **The live V1 'Evaluate Climate Risks' notebook shows the `severe` class only.** It is hard-wired\n")
md("> to that class; the moderate and extreme columns below are published but not surfaced there (#20).\n\n")

md("## Generic crop hazards\n\n")
md("These are the thresholds behind the published `NDWS+NTx35+NDWL0` set, which is what the live V1\n")
md("notebook reads.\n\n")
g <- wide[crop == "generic" & !index_name %like% "THI"]
md("| hazard | index | moderate | severe | extreme |\n|---|---|---|---|---|\n")
for (i in seq_len(nrow(g))) md("| %s | `%s` | %s | %s | %s |\n", g$type[i], g$index_name[i],
  fmt(g$Moderate[i], g$direction[i], g$unit[i]), fmt(g$Severe[i], g$direction[i], g$unit[i]), fmt(g$Extreme[i], g$direction[i], g$unit[i]))

md("\n## Livestock heat stress (THI), per species-system\n\n")
md("Provenance for these classes: `metadata/THI_thresholds_provenance.md`.\n\n")
t <- wide[index_name %like% "THI" & crop != "generic"]
md("| species-system | index | moderate | severe | extreme |\n|---|---|---|---|---|\n")
for (i in seq_len(nrow(t))) md("| %s | `%s` | %s | %s | %s |\n", t$crop[i], t$index_name[i],
  fmt(t$Moderate[i], t$direction[i], t$unit[i]), fmt(t$Severe[i], t$direction[i], t$unit[i]), fmt(t$Extreme[i], t$direction[i], t$unit[i]))
gt <- wide[index_name %like% "THI" & crop == "generic"]
if (nrow(gt)) {
  md("\nGeneric THI fallback, for a species-system with no row of its own:\n\n")
  md("| applies to | index | moderate | severe | extreme |\n|---|---|---|---|---|\n")
  for (i in seq_len(nrow(gt))) md("| %s | `%s` | %s | %s | %s |\n", gt$crop[i], gt$index_name[i],
    fmt(gt$Moderate[i], gt$direction[i], gt$unit[i]), fmt(gt$Severe[i], gt$direction[i], gt$unit[i]), fmt(gt$Extreme[i], gt$direction[i], gt$unit[i]))
}

## crop-specific heat: derived per crop at runtime from ecocrop, so not enumerable from
## haz_classes.csv. Describe the families and the formulas rather than list 35 crops x 9 values.
md("\n## Crop-specific heat thresholds\n\n")
md("Three heat index families are derived **per crop** from `metadata/ecocrop.csv` at run time\n")
md("(`R/2_calculate_haz_freq.R` §0.2.2.1), so they do not appear in `haz_classes.csv`:\n\n")
md("| family | temperature threshold | exceedance days (mod / sev / ext) |\n|---|---|---|\n")
md("| `NTxM` | `Temp_Opt_Max` | 7 / 14 / 21 |\n")
md("| `NTxS` | `ceil((Temp_Opt_Max + Temp_Abs_Max) / 2)` | 7 / 14 / 21 |\n")
md("| `NTxE` | `Temp_Abs_Max` | 1 / 5 / 10 |\n\n")
mz <- eco[species == "Zea mays"][1]
md("Worked example, maize (`Zea mays`: `Temp_Opt_Max` = %s, `Temp_Abs_Max` = %s): `NTxM` = %s °C, ",
   mz$Temp_Opt_Max, mz$Temp_Abs_Max, mz$Temp_Opt_Max)
md("`NTxS` = %s °C, `NTxE` = %s °C.\n\n", ceiling((as.numeric(mz$Temp_Opt_Max) + as.numeric(mz$Temp_Abs_Max)) / 2), mz$Temp_Abs_Max)
md("**`NTxM` is the family wired into the published crop-specific sets** (changed from `NTxS` in\n")
md("2026-10, issue #25: `NTxS` averages the optimum with the *survival* limit, which for maize gives\n")
md("40 °C and reported zero heat-exposed value). All three are classified; only the wired one reaches\n")
md("a published hazard set. Ecocrop is an ecological envelope rather than an agronomic one, so these\n")
md("are under review (#14, #24, #25).\n\n")

md("## Published hazard sets\n\n")
md("Each set is a three-way interaction of a dry, a heat and a wet index. The `hazard_vars` column of\n")
md("the published parquet carries these strings.\n\n")
md("| `hazard_vars` | heat | dry / wet framing | applies to |\n|---|---|---|---|\n")
md("| `NDWS+NTx35+NDWL0` | generic, 35 °C | water balance | crops — **this is what the live V1 notebook reads** |\n")
md("| `NDWS+NTxM+NDWL0` | crop-specific | water balance | crops (new in 2026-10, #25) |\n")
md("| `PTOT-L+NTxM+PTOT-G` | crop-specific | precipitation total | crops (was `PTOT-L+NTxS+PTOT-G`) |\n")
md("| `NDWS+THI-max+NDWL0` | species-specific | water balance | livestock |\n")
md("| `PTOT-L+THI-max+PTOT-G` | species-specific | precipitation total | livestock |\n\n")
md("Definitions of each index: the hazards wiki. THI provenance: `metadata/THI_thresholds_provenance.md`.\n")

cat(sprintf("wrote %s\n", OUT_MD))

## ----------------------------------------------------------------- guards
# #20 itself: the value the notebook misstated.
stopifnot("NTx35 severe must be 14 (#20)" = cls[index_name == "NTx35" & description == "Severe", threshold] == 14)
# the #13 fix, so this table cannot quietly ship the pre-fix threshold
stopifnot("poultry_highland THI_max extreme must be 89 (#13)" =
            cls[index_name == "THI_max" & crop == "poultry_highland" & description == "Extreme", threshold] == 89)
# every classified index must have a unit, or the table prints a bare number
.nu <- d[is.na(unit), unique(index_name)]
if (length(.nu)) stop("no unit in haz_metadata.csv for: ", paste(.nu, collapse = ", "))
# the crop-specific formulas above are COPIED from R/2; fail loudly if R/2's derivation moves, rather
# than letting this table drift from the pipeline the way the notebook prose did
r2 <- readLines(file.path(root, "R", "2_calculate_haz_freq.R"))
stopifnot("R/2 no longer derives NTxM from Temp_Opt_Max - update this generator" =
            any(grepl('paste0\\("NTxM", ecrop\\$Temp_Opt_Max\\)', r2)))
stopifnot("R/2 no longer derives NTxE from Temp_Abs_Max - update this generator" =
            any(grepl('paste0\\("NTxE", ecrop\\$Temp_Abs_Max\\)', r2)))
stopifnot("R/2 no longer wires NTxM as the crop heat family - update this generator" =
            any(grepl('heat_simple = c\\("NTx35", "NTxM", "NTxM"\\)', r2)))
cat("guards passed: NTx35 severe = 14, poultry_highland extreme = 89, units complete, R/2 derivation unchanged\n")
