# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mk_sen_cpp <- function(x, conf_level = 0.95) {
    .Call(`_trendkernel_mk_sen_cpp`, x, conf_level)
}

lag1_ac_cpp <- function(detr) {
    .Call(`_trendkernel_lag1_ac_cpp`, detr)
}

