// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mk_sen_cpp
List mk_sen_cpp(NumericVector x, double conf_level);
RcppExport SEXP _trendkernel_mk_sen_cpp(SEXP xSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(mk_sen_cpp(x, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// lag1_ac_cpp
double lag1_ac_cpp(NumericVector detr);
RcppExport SEXP _trendkernel_lag1_ac_cpp(SEXP detrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type detr(detrSEXP);
    rcpp_result_gen = Rcpp::wrap(lag1_ac_cpp(detr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_trendkernel_mk_sen_cpp", (DL_FUNC) &_trendkernel_mk_sen_cpp, 2},
    {"_trendkernel_lag1_ac_cpp", (DL_FUNC) &_trendkernel_lag1_ac_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_trendkernel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
